08-authentication
js-tasks-ru/nodejs-20210126_detrimon pull request #5
Opened 2021-02-23 08:28 UTC by Detrimon

01-local

2021-02-23 08:28 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-02-23 08:33 UTC, tadjik1 commented on 08-authentication/01-local/libs/strategies/local.js
> +      await User.findOne({'email': email}, async function(err, account) {
либо промис (await), либо callback - не стоит смешивать эти два подхода.

2021-02-23 08:34 UTC, tadjik1 requested changes
@Detrimon  надо выбрать один подход к работе с монгузом и оставить либо промисы, либо коллбек. в данном случае на мой взгляд нет большой разницы что именно выбрать, но выбрать надо что-то одно

2021-02-23 09:15 UTC, Detrimon commented on 08-authentication/01-local/libs/strategies/local.js
> +      await User.findOne({'email': email}, async function(err, account) {
Убрал async / await, вместо него .then добавил

2021-02-23 09:58 UTC, Detrimon commented on 08-authentication/01-local/libs/strategies/local.js
> +      await User.findOne({'email': email}, async function(err, account) {
Может я не совсем понял, но речь идет о том, что в целом по коду лучше не миксовать колбэки и промисы или про конкретно 6 строку, где объявлена async функция, но при этом данной функции передается callback done?

2021-02-23 12:09 UTC, Detrimon commented
> @Detrimon надо выбрать один подход к работе с монгузом и оставить либо промисы, либо коллбек. в данном случае на мой взгляд нет большой разницы что именно выбрать, но выбрать надо что-то одно

Сергей, не совсем понял, как можно функцию account.checkPassword(password) в callback превратить, если, например, только callback'и использовать.

2021-02-25 09:22 UTC, tadjik1 commented
@Detrimon вы всё верно поняли. я говорил в общем, что правильнее не миксовать подходы, но имел ввиду 8 строку - там где в монгуз передавался коллбек. 
в конкретном этом случае мы не сможем целиком уйти от коллбека done(), и не может уйти от промисов (из-за checkPassword), это правда, но с другой стороны не стоит добавлять еще больше подходов :)

2021-02-25 09:22 UTC, tadjik1 approved these changes
прекрасное решение! 👍

2021-02-25 09:22 UTC, merged